#SkyEngine dedicated server configuration
#Tue Sep 01 19:20:33 CEST 2026
authentication=offline
autosave-interval-ticks=1200
bind-address=0.0.0.0
chunk-bytes-per-second=4194304
compression=zstd
compression-level=1
compression-threshold=1024
keepalive-interval=5
max-decompressed-packet-size=8388608
max-packet-size=2097152
max-players=8
motd=SkyEngine Server
server-port=25565
simulation-distance=10
tick-rate=20
timeout=30
view-distance=16
worker-threads=20
world=world
