package de.skyengine.shared.gameplay;

/** Stable protocol-level names for cosmetic sounds emitted by authoritative world logic. */
public enum WorldSoundType {
    HIT, BREAK, PLACE, COMPARATOR_CLICK, LEVER_CLICK, EXPLOSION, FUSE,
    PISTON_EXTEND, PISTON_CONTRACT, FIZZ, FLUID_EXTINGUISH,
    WATER_AMBIENT, LAVA_AMBIENT, LAVA_POP, IGNITE,
    PORTAL_AMBIENT, PORTAL_TRIGGER, PORTAL_TRAVEL,
    DISPENSER_SUCCESS, DISPENSER_FAILURE, BUCKET_EMPTY, BUCKET_FILL,
    ITEM_FRAME_REMOVE_ITEM, ITEM_FRAME_BREAK, BLOCK_OPEN, BLOCK_CLOSE
}
